'use client';
import {useState} from 'react';
import {attention,hstuWeights,kvBytes,maskedMse} from '@/lib/learning/math';
import type {Locale} from '@/lib/learning/tracks';
function Matrix({values,label}:{values:number[][],label:string}) {return <div className="matrix-scroll"><table className="lab-matrix"><caption>{label}</caption><thead><tr><th>Q / K</th>{values.map((_,i)=><th key={i}>t{i}</th>)}</tr></thead><tbody>{values.map((r,i)=><tr key={i}><th>t{i}</th>{r.map((v,j)=><td key={j} style={{background:v<0?'#f7c7bc':`rgba(33,108,130,${Math.min(.8,Math.abs(v))*.8+.05})`}}>{v.toFixed(3)}</td>)}</tr>)}</tbody></table></div>}
export function ConceptLab({kind,locale}:{kind:string,locale:Locale}){
 const zh=locale==='zh-CN';const [temp,setTemp]=useState(1),[causal,setCausal]=useState(true),[tokens,setTokens]=useState(4096),[batch,setBatch]=useState(4),[heads,setHeads]=useState(8),[bias,setBias]=useState(.5),[ratio,setRatio]=useState(.75),[fill,setFill]=useState(.5),[seed,setSeed]=useState(0);
 const mask=Array.from({length:64},(_,i)=>((i*37+seed*13)%64)<Math.round(ratio*64));const target=mask.map((_,i)=>(Math.sin(i*.65)+1)/2);
 return <section className="concept-lab" id="interactive-lab"><p className="section-kicker">{zh?'交互实验 · 实时数值计算':'INTERACTIVE LAB · LIVE NUMERICAL COMPUTATION'}</p>
 {kind==='attention'&&<><h2>{zh?'注意力的每一行，究竟在分配什么？':'What does each attention row distribute?'}</h2><p>{zh?'固定 Q=K=[[1,0],[0,1],[1,1],[-1,0.5]]，观察 softmax(QKᵀ/√2/T)。这些是教学向量，不是模型提取的注意力。':'Fixed Q=K=[[1,0],[0,1],[1,1],[-1,0.5]]. Observe softmax(QKᵀ/√2/T). These are teaching vectors, not extracted model attention.'}</p><label>{zh?'温度':'Temperature'} T = {temp.toFixed(1)}<input type="range" min=".1" max="3" step=".1" value={temp} onChange={e=>setTemp(+e.target.value)}/></label><label className="lab-check"><input type="checkbox" checked={causal} onChange={e=>setCausal(e.target.checked)}/>{zh?'启用因果遮罩':'Causal mask'}</label><Matrix values={attention(temp,causal)} label={zh?'行是 query，列是 key；每行总和 = 1':'Rows are queries; columns are keys. Each row sums to 1.'}/><p>{zh?'试一试：关闭遮罩后，第一个 token 能看到未来了。温度接近 0 时，每行集中到最大分数，但并列最大值仍会平分。':'Try removing the mask: the first token can now see the future. Near zero temperature, mass concentrates on the largest scores; ties still share it.'}</p></>}
 {kind==='infra'&&<><h2>{zh?'KV cache 显存预算':'KV-cache memory budget'}</h2><p>{zh?'假设 32 层、head dimension 128、FP16/BF16 每元素 2 bytes。只估算 KV，不包含权重、激活、分页余量或运行时工作区。':'Assume 32 layers, head dimension 128 and 2 bytes per FP16/BF16 element. KV only: weights, activations, page slack and runtime workspaces are excluded.'}</p><label>{zh?'每条序列 token 数':'Tokens per sequence'}: {tokens}<input type="range" min="512" max="32768" step="512" value={tokens} onChange={e=>setTokens(+e.target.value)}/></label><label>{zh?'并发序列数':'Concurrent sequences'}: {batch}<input type="range" min="1" max="64" value={batch} onChange={e=>setBatch(+e.target.value)}/></label><label>{zh?'KV heads':'KV heads'}<select value={heads} onChange={e=>setHeads(+e.target.value)}><option value="32">MHA · 32</option><option value="8">GQA · 8</option><option value="1">MQA · 1</option></select></label><output className="lab-big-number">{(kvBytes(batch,tokens,32,heads,128,2)/2**30).toFixed(2)} <small>GiB</small></output><p><code>2 × B × T × L × Hkv × Dh × bytes</code></p><p>{zh?'改成 1 个 KV head 会缩小缓存，但这是模型架构选择，不是可以无损任意修改的推理开关。分片后的每卡值还取决于 KV heads 是否被复制。':'One KV head reduces cache, but changing head count is an architecture choice, not a lossless serving toggle. Per-device memory also depends on whether KV heads are replicated.'}</p></>}
 {kind==='patches'&&<><h2>{zh?'遮住 patch，只在隐藏位置计算损失':'Mask patches; measure loss only on hidden positions'}</h2><p>{zh?'8×8 合成灰度网格。调整遮罩位置与常数预测，观察 masked MSE。这不是训练过的 MAE，真实权重重建在本路线 Notebook。':'An 8×8 synthetic grayscale grid. Adjust the mask and constant predictor to inspect masked MSE. This is not a trained MAE; the notebook runs real pretrained reconstruction.'}</p><label>{zh?'遮罩比例':'Mask ratio'}: {ratio.toFixed(2)}<input type="range" min="0" max=".95" step=".05" value={ratio} onChange={e=>setRatio(+e.target.value)}/></label><label>{zh?'隐藏 patch 的预测灰度':'Predicted intensity for hidden patches'}: {fill.toFixed(2)}<input type="range" min="0" max="1" step=".05" value={fill} onChange={e=>setFill(+e.target.value)}/></label><button onClick={()=>setSeed(s=>s+1)}>{zh?'改变遮罩位置':'Change mask positions'}</button><div className="patch-panels">{[false,true].map(pred=><figure key={String(pred)}><div className="patch-grid">{target.map((v,i)=><span key={i} title={`patch ${i}: ${v.toFixed(3)}; ${mask[i]?'masked':'visible'}`} style={{background:`rgb(${Math.round((pred&&mask[i]?fill:v)*255)} ${Math.round((pred&&mask[i]?fill:v)*255)} ${Math.round((pred&&mask[i]?fill:v)*255)})`,outline:mask[i]?'2px solid #d94b32':undefined}}/>)}</div><figcaption>{pred?(zh?'填补后（红框是隐藏位置）':'Filled (red = masked)'):(zh?'原始目标':'Original target')}</figcaption></figure>)}</div><output>Masked MSE = {maskedMse(target,target.map(()=>fill),mask).toFixed(5)} · {mask.filter(Boolean).length}/64 {zh?'隐藏':'masked'}</output><p>{zh?'零遮罩时没有重建训练信号，显示 0 只是空集合约定，不能表示模型预测完美。':'With no masked patches there is no reconstruction supervision; zero is an empty-set convention, not perfect prediction.'}</p></>}
 {kind==='hstu'&&<><h2>{zh?'HSTU 式聚合不要求权重和为 1':'HSTU-style aggregation need not sum to one'}</h2><p>{zh?'固定二维 Q/K，因果遮罩，教学时间偏置 −α(i−j)。显示 SiLU(QKᵀ+bias)/4；完整 HSTU 还有 U/V 投影、归一化、门控和残差。':'Fixed 2D Q/K, a causal mask and teaching bias −α(i−j). Displaying SiLU(QKᵀ+bias)/4; full HSTU also includes U/V projections, normalization, gating and a residual.'}</p><label>{zh?'时间衰减强度':'Temporal bias strength'} α = {bias.toFixed(1)}<input type="range" min="0" max="3" step=".1" value={bias} onChange={e=>setBias(+e.target.value)}/></label><Matrix values={hstuWeights(bias)} label={zh?'可以为负；这些不是概率':'Weights may be negative; these are not probabilities'}/><p>{zh?'每行的总和':'Row sums'}: {hstuWeights(bias).map(r=>r.reduce((a,b)=>a+b,0).toFixed(3)).join(' / ')}</p><p>{zh?'增大 α 后，过去位置可能得到负值而不是概率意义上的“较少关注”。不要把 softmax 的熵分析直接用于这张矩阵。':'Increasing α can make earlier positions negative, rather than simply less probable. Softmax entropy analysis does not apply to this matrix.'}</p></>}
 </section>
}
