'use client';
import {useEffect,useRef,useState} from 'react';
import type {Locale} from '@/lib/learning/tracks';
type Result={cosine:number;embeddings:number[][];ids:number[][];masks:number[][];tokens:string[][];dims:number[]};
export function ModelInspector({locale}:{locale:Locale}){
 const zh=locale==='zh-CN';const [texts,setTexts]=useState(['A cat is sleeping on the sofa.','A kitten is resting on a couch.']);const [result,setResult]=useState<Result|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const worker=useRef<Worker|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),runId=useRef(0);
 function cleanup(){worker.current?.terminate();worker.current=null;if(timer.current)clearTimeout(timer.current)}
 useEffect(()=>()=>{worker.current?.terminate();if(timer.current)clearTimeout(timer.current)},[]);
 function stop(){cleanup();runId.current++;setBusy(false);setStatus(zh?'已停止，可重试。':'Stopped. You can retry.')}
 function run(){cleanup();setResult(null);setBusy(true);setStatus(zh?'正在下载运行库与模型权重…':'Downloading runtime and model weights…');const id=++runId.current;try{const w=new Worker('/workers/model-inspector.mjs',{type:'module'});worker.current=w;const fail=(message:string)=>{cleanup();setBusy(false);setStatus(message)};w.onerror=e=>fail((zh?'运行失败：':'Runtime error: ')+e.message);w.onmessage=({data})=>{if(data.runId!==id)return;if(data.type==='progress')setStatus(`${data.status}: ${data.file} ${data.progress===null?'':Math.round(data.progress)+'%'}`);if(data.type==='error')fail((zh?'模型未运行成功，可重试或使用 Notebook。':'Model failed. Retry or use the notebook. ')+data.message);if(data.type==='result'){setResult(data);setBusy(false);setStatus(zh?'完成 · 以下为真实模型输出':'Complete · actual model output');cleanup()}};w.postMessage({texts,runId:id});timer.current=setTimeout(()=>fail(zh?'运行超过 3 分钟，已终止。请检查网络后重试，或使用 Notebook。':'Stopped after 3 minutes. Check connectivity and retry, or use the notebook.'),180000)}catch(e){failLocal(String(e))}}
 function failLocal(message:string){cleanup();setBusy(false);setStatus(message)}
 return <section className="concept-lab" id="model-inspector"><p className="section-kicker">PRETRAINED MODEL · MiniLM-L6 · WASM / CPU</p><h2>{zh?'加载真实模型，看见 token 和 embedding':'Load a real model. Inspect tokens and embeddings.'}</h2><p>{zh?'点击后从 Hugging Face 下载量化模型（约 23 MB 权重，另需运行库）。文本在本地浏览器计算，不发送给推理服务。需要能访问 Hugging Face 与 jsDelivr。这个模型主要面向英文，不是聊天大模型；最多处理 128 tokens。':'On click, download quantized weights from Hugging Face (~23 MB plus runtime). Text is processed locally, not sent to an inference service. Requires Hugging Face and jsDelivr access. This is primarily an English embedding model, not a chat LLM; inputs are capped at 128 tokens.'}</p>{texts.map((text,i)=><label key={i}>{zh?'句子':'Sentence'} {i+1}<textarea disabled={busy} maxLength={1000} value={text} onChange={e=>{setTexts(old=>old.map((v,j)=>j===i?e.target.value:v));setResult(null);setStatus('')}}/></label>)}<div className="lab-actions"><button disabled={busy||texts.some(t=>!t.trim())} onClick={run}>{zh?'下载模型并运行':'Download model & run'}</button><button disabled={!busy} onClick={stop}>{zh?'停止':'Stop'}</button></div><p role="status" aria-live="polite">{status}</p>{result&&<><output className="lab-big-number">{result.cosine.toFixed(4)} <small>{zh?'余弦相似度':'cosine similarity'}</small></output><p>{zh?'归一化输出形状':'Normalized output shape'}: [{result.dims.join(', ')}]</p>{result.tokens.map((row,i)=><div key={i}><h3>{zh?'句子':'Sentence'} {i+1}</h3><div className="token-strip">{row.map((token,j)=><span key={j} style={{opacity:result.masks[i][j]?1:.4}}>{token}<small>{result.ids[i][j]} · mask {result.masks[i][j]}</small></span>)}</div></div>)}<h3>{zh?'前 32 个 embedding 维度':'First 32 embedding dimensions'}</h3><div className="embedding-bars">{result.embeddings[0].slice(0,32).map((v,i)=><div key={i} title={`dim ${i}: ${v}`} style={{height:`${Math.max(3,Math.abs(v)*650)}px`,background:v<0?'#d94b32':'#216c82'}}/>)}</div><p>{zh?'维度没有固定的人类语义；条形图不是注意力图。余弦相似度也不是“正确概率”。':'Dimensions have no fixed human meaning. This is not an attention map, and cosine similarity is not a probability of correctness.'}</p><details><summary>{zh?'查看完整输入与输出 JSON':'Inspect full input/output JSON'}</summary><pre>{JSON.stringify(result,null,2)}</pre></details></>}</section>
}
