'use client';
import {useEffect,useRef,useState} from 'react';
import type {Locale} from '@/lib/learning/tracks';
const snippets:Record<string,string>={
'llm-foundations':`import math\n# Change the logits and temperature, then predict the output.\nlogits = [2.0, 1.0, -1.0]\ntemperature = 0.8\nassert temperature > 0\nz = [math.exp((x-max(logits))/temperature) for x in logits]\np = [x/sum(z) for x in z]\nprint("probabilities:", [round(x, 4) for x in p])\nprint("sum:", sum(p))\nprint("target=0, NLL:", -math.log(p[0]))`,
'llm-infra':`# FP16 weights/gradients + FP32 master weights + Adam moments.\nparameters = 7_000_000_000\nranks = 8\nassert ranks > 0\nfor stage in range(4):\n    weights = 2*parameters / (ranks if stage >= 3 else 1)\n    grads = 2*parameters / (ranks if stage >= 2 else 1)\n    optimizer = 12*parameters / (ranks if stage >= 1 else 1)\n    print("ZeRO",stage,"GiB per rank:",round((weights+grads+optimizer)/2**30, 2))\nprint("Excludes activations, gathered layers, communication buffers.")`,
'multimodal':`import math\n# A two-pair contrastive objective. Rows=image, columns=text.\nsimilarity = [[0.8, 0.2], [0.3, 0.7]]\ntemperature = 0.1\nassert temperature > 0\nlosses = []\nfor i, row in enumerate(similarity):\n    z = [math.exp((x-max(row))/temperature) for x in row]\n    p = [x/sum(z) for x in z]\n    losses.append(-math.log(p[i]))\n    print("image",i,"probabilities:",p)\nprint("Image-to-text mean loss:",sum(losses)/len(losses))\nprint("CLIP also trains the reverse text-to-image direction.")`,
'hstu':`import math\n# Educational HSTU-like aggregation; these are not probabilities.\nq = [1.0, 0.5]\nkeys = [[1.0, 0.0], [0.0, 1.0], [-1.0, 0.5]]\nvalues = [[1.0, 2.0], [3.0, 1.0], [0.0, 4.0]]\nscores = [sum(a*b for a,b in zip(q,k)) for k in keys]\nweights = [s/(1+math.exp(-s))/len(keys) for s in scores]\noutput = [sum(w*v[d] for w,v in zip(weights,values)) for d in range(2)]\nprint("weights:",weights,"sum:",sum(weights))\nprint("aggregated V:",output)\nprint("Full block: normalize, gate by U, project, add residual.")`};
export function PythonLab({track,locale}:{track:string,locale:Locale}){
 const zh=locale==='zh-CN';const initial=snippets[track]??snippets['llm-foundations'];const [code,setCode]=useState(initial),[output,setOutput]=useState(''),[busy,setBusy]=useState(false);const worker=useRef<Worker|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{worker.current?.terminate();if(timer.current)clearTimeout(timer.current)},[]);
 function stop(){worker.current?.terminate();worker.current=null;if(timer.current)clearTimeout(timer.current);setBusy(false)}
 function run(){stop();setBusy(true);setOutput(zh?'首次运行正在加载 Python…':'Loading Python for the first run…');try{const w=new Worker('/workers/generative-lab-worker.mjs',{type:'module'});worker.current=w;w.onmessage=({data})=>{if(data.type==='result'||data.type==='error'){setOutput(data.output|| (zh?'运行完成，无输出。':'Finished without output.'));stop()}};w.onerror=e=>{setOutput(e.message);stop()};w.postMessage({code,runId:1});timer.current=setTimeout(()=>{stop();setOutput(zh?'运行超时，已停止。可修改代码后重试。':'Execution timed out. Edit the code and retry.')},60000)}catch(e){stop();setOutput(String(e))}}
 return <section className="concept-lab" id="editable-python"><p className="section-kicker">PYTHON · WEBASSEMBLY · NO GPU</p><h2>{zh?'改代码，再验证你的预测':'Edit the code and test your prediction'}</h2><p>{zh?'真实 Python 在独立 Worker 中运行，只用标准库；60 秒自动终止。完整 PyTorch 和模型权重实验请打开 Notebook。':'Real Python runs in a separate worker, using the standard library, with a 60-second limit. Use the notebook for PyTorch and pretrained model experiments.'}</p><label>{zh?'Python 代码':'Python code'}<textarea className="python-editor" spellCheck={false} value={code} onChange={e=>setCode(e.target.value)} disabled={busy}/></label><div className="lab-actions"><button onClick={run} disabled={busy}>{zh?'运行 Python':'Run Python'}</button><button onClick={()=>{stop();setOutput(zh?'已停止':'Stopped')}} disabled={!busy}>{zh?'停止':'Stop'}</button><button onClick={()=>{setCode(initial);setOutput('')}} disabled={busy}>{zh?'恢复示例':'Reset code'}</button></div><pre role="status" aria-live="polite">{output||(zh?'运行后显示实际输出。':'Actual output appears after running.')}</pre></section>
}
