import type { Metadata } from 'next';
import { SiteHeader, SiteFooter } from '@/app/components/SiteHeader';
import { tracks, type Locale } from '@/lib/learning/tracks';
import { posts } from '@/lib/posts';
import { absoluteUrl, serializeJsonLd, RSS_ALTERNATE } from '@/lib/site';
export function learningMetadata(locale:Locale, id?:string): Metadata {
 const track=tracks.find(t=>t.id===id); const base=id?`/learn/${id}`:'/learn';
 const title=track?.title[locale]??(locale==='en'?'The model learning studio':'模型学习工作台');
 const description=track?.description[locale]??(locale==='en'?'Four bilingual learning paths with interactive experiments and reproducible notebooks.':'四条双语学习路线，结合交互实验、原理图与可复现 Notebook。');
 return {title:`${title} — Huiyu Chen`,description,alternates:{canonical:base+(locale==='en'?'/en':''),languages:{'zh-CN':base,en:base+'/en','x-default':base+'/en'},types:RSS_ALTERNATE},openGraph:{title,description,type:'website',url:base+(locale==='en'?'/en':'')}};
}
export function LearningPage({locale}:{locale:Locale}) {
 const zh=locale==='zh-CN';
 return <main className="site-shell learning-shell" id="top" lang={locale}><SiteHeader/><header className="learning-intro"><p className="section-kicker">THE MODEL LEARNING STUDIO · 01—04</p><a className="language-switch" href={zh?'/learn/en':'/learn'}>{zh?'Read in English →':'阅读中文版 →'}</a><h1>{zh?'把模型拆开，\n再亲手运行。':'Take models apart.\nThen run them.'}</h1><p>{zh?'从零建立直觉，用张量和代码验证理解。每条路线都包含完整中英文章、可操作的实验和进阶阅读。':'Build intuition from first principles, then verify it with tensors and code. Each path includes complete bilingual chapters, working experiments and deeper reading.'}</p></header><section className="learning-tracks">{tracks.map(t=>{const chapters=posts.filter(p=>p.series===t.id&&p.language===locale);return <a className="learning-track" href={`/learn/${t.id}${zh?'':'/en'}`} key={t.id}><span className="learning-number">{t.no}</span><div><p className="section-kicker">{t.tags.join(' / ')}</p><h2>{t.title[locale]}</h2><p>{t.description[locale]}</p><span>{chapters.length} {zh?'章 · 原理 / 实验 / Notebook':'chapters · theory / experiments / notebook'} ↗</span></div></a>})}</section><section className="learning-method"><h2>{zh?'按问题学习，不必一次读完。':'Follow a question. You do not need to read everything at once.'}</h2><p>{zh?'第一次接触大模型？从路线 01 开始。模型太慢？进入路线 02。处理图文视频？从路线 03 的 patch 和对齐入手。研究推荐？在路线 04 里沿着行为时间轴动手。':'New to language models? Begin with 01. Serving too slowly? Explore 02. Working with images and video? Start with patches and alignment in 03. Studying recommendation? Follow the action timeline in 04.'}</p><p>{zh?'实验标明计算方式：教学数值模型、浏览器内真实预训练模型、或需要 Python / GPU 的 Notebook。估算值不代表硬件实测。':'Every experiment states its execution mode: a numerical teaching model, a real pretrained browser model, or a Python/GPU notebook. Estimates are not hardware measurements.'}</p></section><SiteFooter/></main>;
}
export function TrackPage({locale,id}:{locale:Locale,id:string}) {
 const t=tracks.find(t=>t.id===id)!; const zh=locale==='zh-CN';const chapters=posts.filter(p=>p.series===id&&p.language===locale).sort((a,b)=>(a.seriesOrder??0)-(b.seriesOrder??0));
 return <main className="site-shell learning-shell" id="top" lang={locale}><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:t.title[locale],url:absoluteUrl(`/learn/${id}${zh?'':'/en'}`),inLanguage:locale,hasPart:chapters.map(p=>({'@type':'Article',name:p.title,url:absoluteUrl('/blog/'+p.slug)}))})}}/><header className="learning-intro"><a href={zh?'/learn':'/learn/en'}>← {zh?'全部学习路线':'All learning paths'}</a><a className="language-switch" href={`/learn/${id}${zh?'/en':''}`}>{zh?'Read in English →':'阅读中文版 →'}</a><p className="section-kicker">PATH {t.no} · {chapters.length} {zh?'章':'CHAPTERS'}</p><h1>{t.title[locale]}</h1><p>{t.description[locale]}</p></header><div className="learning-course"><aside><h2>{zh?'学习方式':'How to learn'}</h2><p>{zh?'先预测输出，再改参数观察，最后打开代码验证。每章结尾有练习和答案。':'Predict the output, change a parameter, then check the code. Every chapter includes an exercise and its answer.'}</p><a href={`https://colab.research.google.com/github/chenhuiyu/chenhuiyu.github.io/blob/source/public/notebooks/${t.notebook}-${locale}.ipynb`} target="_blank" rel="noreferrer">{zh?'在 Colab 打开实验 ↗':'Open companion in Colab ↗'}</a><a download href={`/notebooks/${t.notebook}-${locale}.ipynb`}>{zh?'下载 Notebook ↓':'Download notebook ↓'}</a><p>{zh?'Notebook 的环境要求和执行状态见首个单元。':'Environment requirements and execution status are in the first cell.'}</p></aside><ol className="learning-chapters">{chapters.map(p=><li key={p.slug}><a href={'/blog/'+p.slug}><span>{String(p.seriesOrder).padStart(2,'0')}</span><div><h2>{p.title}</h2><p>{p.excerpt}</p></div><span aria-hidden="true">↗</span></a></li>)}</ol></div><SiteFooter/></main>;
}
