import { b, type Question, type Localized, type Case, type Difficulty } from './schema';
function code(id:number,topic:string,difficulty:Difficulty,title:Localized,prompt:Localized,starter:string,solution:string,tests:Case[],explanation:Localized,complexity:Localized,followup:Localized):Question {
 return {id:String(id).padStart(3,'0'),topic,difficulty,kind:'code',title,prompt,starter,solution,tests,explanation,complexity,followup};
}
export const coding:Question[]=[
code(49,'foundations','easy',b('实现稳定 Softmax','Implement stable softmax'),b('实现 softmax(logits)，返回与输入等长的概率列表。输入是有限实数列表；空列表返回 []。必须处理 1000、-1000 等大幅值，不能直接对原 logits 全部取 exp。允许 math 标准库。测试浮点容差为 1e-6。','Implement softmax(logits), returning a probability list of equal length. Inputs are finite real numbers; return [] for empty input. Handle large values such as 1000 and -1000 without directly exponentiating raw logits. The math standard library is allowed. Floating-point tolerance is 1e-6.'),'def softmax(logits):\n    # Return a list of probabilities.\n    pass\n',
`import math
def softmax(logits):
    if not logits:
        return []
    maximum = max(logits)
    weights = [math.exp(x - maximum) for x in logits]
    total = sum(weights)
    return [x / total for x in weights]
`,[{expression:'softmax([0, 0])',expected:[.5,.5]},{expression:'softmax([1000, 1000])',expected:[.5,.5]},{expression:'softmax([])',expected:[]},{expression:'softmax([-1000])',expected:[1]},{expression:'softmax([0, 1, 2])',expected:[.09003057317,.24472847105,.66524095577]},{expression:'softmax([-1000, 0, 1000])',expected:[0,0,1]}],b('给所有 logits 减去同一个常数，分子分母都会乘上相同因子，因此概率不变。减去最大值后，最大的 exp 为 1，避免上溢。\n\n先处理空列表，再计算最大值。这里约定输入有限；包含 +∞ 或全为 −∞ 的输入需要额外语义，不在本题范围内。','Subtracting a shared constant scales numerator and denominator equally, leaving probabilities unchanged. Subtracting the maximum keeps the largest exponential at one and prevents overflow.\n\nHandle the empty list first. Infinite inputs or all-negative-infinity rows need additional semantics and are outside this problem.'),b('时间 O(n)，输出及临时空间 O(n)。','O(n) time and O(n) output/temporary space.'),b('若某一行被 mask 到全是 −∞，你会怎样定义输出？','How would you define output for an entirely masked row?')),
code(50,'architecture','hard',b('纯 Python Causal Attention','Causal attention in pure Python'),b('实现 causal_attention(q,k,v)。q、k 是 n×d 矩阵，v 是 n×dv；n,d,dv 均为正，形状有效且数值有限。位置 i 只能读取 j≤i。返回 n×dv 的 softmax(QKᵀ/√d)V，必须稳定计算 softmax。不要修改输入，不使用 NumPy。','Implement causal_attention(q,k,v). q and k are n×d, v is n×dv; all dimensions are positive, shapes are valid and values finite. Position i can read only j≤i. Return n×dv softmax(QKᵀ/√d)V using stable softmax. Do not mutate inputs or use NumPy.'),'def causal_attention(q, k, v):\n    pass\n',
`import math
def causal_attention(q, k, v):
    scale = math.sqrt(len(q[0]))
    output = []
    for i, query in enumerate(q):
        scores = [sum(a*b for a,b in zip(query,k[j]))/scale for j in range(i+1)]
        maximum = max(scores)
        weights = [math.exp(s-maximum) for s in scores]
        total = sum(weights)
        output.append([sum(weights[j]*v[j][c] for j in range(i+1))/total for c in range(len(v[0]))])
    return output
`,[{expression:'causal_attention([[0],[0]], [[0],[0]], [[2],[6]])',expected:[[2],[4]]},{expression:'causal_attention([[1]], [[2]], [[3,4]])',expected:[[3,4]]},{expression:'causal_attention([[0],[0],[0]], [[0],[0],[0]], [[1],[4],[7]])',expected:[[1],[2.5],[4]]},{expression:'causal_attention([[0,0],[0,0]], [[9,2],[8,1]], [[2,4],[6,8]])',expected:[[2,4],[4,6]]},{expression:'causal_attention([[1000],[1000]], [[1000],[1000]], [[1],[3]])',expected:[[1],[2]]},{expression:'causal_attention([[1],[1]], [[0],[1]], [[0],[1]])',expected:[[0],[.73105857863]]}],b('每行只构造 j≤i 的分数，避免未来位置进入归一化分母。缩放和减最大值后再 softmax，最后对 V 做加权和。\n\n最常见错误是先在整行 softmax，再把未来权重清零而不重新归一化；那样合法位置的权重和不再为 1。','Construct scores only for j≤i so future positions never enter the softmax denominator. Scale, subtract the maximum, normalize, then combine V.\n\nA common bug is softmax over the full row followed by zeroing future weights without renormalization. Allowed weights then no longer sum to one.'),b('时间 O(n²(d+dv))；逐行临时空间 O(n)，另有 O(n·dv) 输出。','O(n²(d+dv)) time; O(n) per-row temporary space plus O(n·dv) output.'),b('怎样只计算 decode 时最新一个 query 的输出？','How would you compute only the latest query during decode?')),
code(51,'training','medium',b('正确聚合 Token Loss','Aggregate token loss correctly'),b('实现 token_mean(loss_sums, counts)。每个 loss_sums[i] 是一个 microbatch 内有效 token 的 NLL 总和，不是均值；counts[i] 是对应非负整数 token 数。列表等长。返回全局 token 均值；总 token 数为 0 时抛 ValueError。不要平均各 microbatch 的均值。','Implement token_mean(loss_sums, counts). Each loss_sums[i] is the sum of valid-token NLLs in one microbatch, not its mean; counts[i] is its nonnegative integer token count. Lists have equal length. Return the global token mean; raise ValueError when total count is zero. Do not average microbatch means.'),'def token_mean(loss_sums, counts):\n    pass\n',
`def token_mean(loss_sums, counts):
    total = sum(counts)
    if total == 0:
        raise ValueError('No valid tokens')
    return sum(loss_sums) / total
`,[{expression:'token_mean([2,18],[1,9])',expected:2},{expression:'token_mean([6,4],[2,1])',expected:10/3},{expression:'token_mean([0,12],[0,3])',expected:4},{expression:'token_mean([2.5],[5])',expected:.5},{expression:'token_mean([],[])',raises:'ValueError'},{expression:'token_mean([0,0],[0,0])',raises:'ValueError'}],b('全局 token 均值是总 NLL 除以总有效 token 数，而不是 microbatch 均值的无权平均。先聚合分子和分母，才能正确处理不同序列长度。\n\n当分母为零时没有可定义的平均 loss，不应该静默返回 0 并假装训练成功。','The global token mean divides total NLL by the total valid-token count, not an unweighted average of microbatch means. Aggregate numerator and denominator separately to handle variable lengths.\n\nA zero denominator means there is no defined mean loss; silently returning zero can hide a data problem.'),b('时间 O(m)，额外空间 O(1)。','O(m) time and O(1) extra space.'),b('分布式训练中，这两个总量应该在哪些进程间归约？','Across which processes should these two totals be reduced?')),
code(52,'alignment','medium',b('数值稳定的 DPO Loss','Numerically stable DPO loss'),b('实现 dpo_loss(pc,pr,rc,rr,beta)。前四项是 policy/reference 对 chosen/rejected 的序列 log probability，均有限；beta 为有限正数。令 z=beta*((pc-pr)-(rc-rr))，返回 -log(sigmoid(z))。需稳定处理 z=±1000。','Implement dpo_loss(pc,pr,rc,rr,beta). The first four finite values are policy/reference sequence log probabilities for chosen/rejected; beta is finite and positive. Let z=beta*((pc-pr)-(rc-rr)); return -log(sigmoid(z)). Handle z=±1000 stably.'),'def dpo_loss(pc, pr, rc, rr, beta):\n    pass\n',
`import math
def dpo_loss(pc, pr, rc, rr, beta):
    z = beta * ((pc-pr)-(rc-rr))
    return max(0.0, -z) + math.log1p(math.exp(-abs(z)))
`,[{expression:'dpo_loss(-2,-2,-2,-2,1)',expected:.69314718056},{expression:'dpo_loss(-1,-3,-2,-2,1)',expected:.12692801104},{expression:'dpo_loss(0,-1000,0,0,1)',expected:0},{expression:'dpo_loss(-1000,0,0,0,1)',expected:1000},{expression:'dpo_loss(-4,-4,-3,-3,.1)',expected:.69314718056},{expression:'dpo_loss(-1,-3,-2,-2,.5)',expected:.31326168752}],b('-log σ(z)=softplus(-z)。稳定写法是 max(0,-z)+log1p(exp(-|z|))，避免 exp(1000) 上溢。\n\nPolicy 与 reference 在同一对答案上的差分必须都保留；遗漏 reference 会改变目标，而不是单纯简化计算。','-log σ(z)=softplus(-z). The stable expression max(0,-z)+log1p(exp(-|z|)) avoids exp(1000) overflow.\n\nKeep both policy and reference differences for the same answer pair. Removing the reference changes the objective, not merely the implementation.'),b('时间和额外空间均 O(1)。','O(1) time and extra space.'),b('为什么 beta 很大时，偏好 margin 的数值稳定性更重要？','Why does numerical stability matter more at large beta?')),
code(53,'serving','easy',b('计算 KV Cache 字节数','Compute KV-cache bytes'),b('实现 kv_bytes(batch,layers,tokens,kv_heads,head_dim,bytes_per_element)。前五项为非负整数，最后一项为正整数。假设每层存完整 K 和 V，忽略分页、对齐和元数据，返回总字节数，不是 GiB。使用 KV head 数而非 query head 数。','Implement kv_bytes(batch,layers,tokens,kv_heads,head_dim,bytes_per_element). The first five are nonnegative integers; the last is positive. Each layer stores full K and V. Ignore paging, alignment and metadata; return bytes, not GiB. Use KV heads, not query heads.'),'def kv_bytes(batch, layers, tokens, kv_heads, head_dim, bytes_per_element):\n    pass\n',
`def kv_bytes(batch, layers, tokens, kv_heads, head_dim, bytes_per_element):
    return 2 * batch * layers * tokens * kv_heads * head_dim * bytes_per_element
`,[{expression:'kv_bytes(1,1,1,1,1,2)',expected:4},{expression:'kv_bytes(2,32,1024,8,128,2)',expected:268435456},{expression:'kv_bytes(1,32,4096,8,128,2)',expected:536870912},{expression:'kv_bytes(4,10,0,8,64,2)',expected:0},{expression:'kv_bytes(1,2,3,4,5,1)',expected:240}],b('K 和 V 各存一份，所以系数为 2。剩余维度依次乘 batch、层数、缓存位置、KV heads、head_dim 和元素字节数。\n\n这只是理论有效数据量，不是进程总显存。分页浪费、共享前缀、量化元数据及分片布局会改变实际每卡占用。','K and V contribute a factor of two. Multiply by batch, layers, cached positions, KV heads, head dimension and bytes per element.\n\nThis is theoretical payload, not total process memory. Paging, shared prefixes, quantization metadata and sharding affect actual per-device allocation.'),b('时间和空间 O(1)，忽略大整数位复杂度。','O(1) time/space, ignoring big-integer bit complexity.'),b('如何把这个公式改成每卡分片后的估算？','How would you adapt this to per-device sharded estimates?')),
code(54,'distributed','easy',b('不整除时的均衡分片','Balance uneven shards'),b('实现 shard_sizes(n,world)。n 是非负整数，world 是正整数。把 n 个连续元素尽量均匀分给 world 个 rank，余数优先分给较小 rank，返回各 rank 元素数；不需要实际复制元素。','Implement shard_sizes(n,world), with nonnegative integer n and positive integer world. Divide n contiguous elements as evenly as possible across world ranks, assigning remainders to smaller ranks first. Return counts only; do not copy the elements.'),'def shard_sizes(n, world):\n    pass\n',
`def shard_sizes(n, world):
    base, remainder = divmod(n, world)
    return [base + (rank < remainder) for rank in range(world)]
`,[{expression:'shard_sizes(10,3)',expected:[4,3,3]},{expression:'shard_sizes(2,4)',expected:[1,1,0,0]},{expression:'shard_sizes(0,3)',expected:[0,0,0]},{expression:'shard_sizes(12,4)',expected:[3,3,3,3]},{expression:'shard_sizes(7,1)',expected:[7]}],b('令 q=n//world，r=n%world。前 r 个 rank 取 q+1，其余取 q，保证总和为 n、最大差值不超过 1。\n\n实际通信有时要求等长张量，需要额外 padding 和有效长度元数据；本题只计算逻辑分片。','Let q=n//world and r=n%world. The first r ranks get q+1 and the rest q, preserving the total and limiting imbalance to one element.\n\nSome collectives need equal-size buffers, requiring padding and valid-length metadata. This problem computes logical partition sizes only.'),b('时间和输出空间 O(world)。','O(world) time and output space.'),b('每个 rank 的起始 offset 如何从这些大小得到？','How do you derive each rank’s starting offset from these sizes?')),
code(55,'hardware','medium',b('实现对称量化','Implement symmetric quantization'),b('实现 quantize(values,bits=8)，返回 [整数列表, scale]。bits 为 2–8 的整数，values 为有限实数列表。qmax=2^(bits-1)-1；scale=max(abs(values))/qmax；q 使用 Python round（ties-to-even）并裁剪到 [-qmax,qmax]。空列表或全零时 scale=1。','Implement quantize(values,bits=8), returning [integer_list, scale]. bits is an integer 2–8; values are finite reals. qmax=2^(bits-1)-1 and scale=max(abs(values))/qmax. Use Python round (ties-to-even), clipping to [-qmax,qmax]. For empty or all-zero inputs use scale=1.'),'def quantize(values, bits=8):\n    pass\n',
`def quantize(values, bits=8):
    qmax = 2**(bits-1)-1
    maximum = max((abs(x) for x in values), default=0)
    scale = maximum/qmax if maximum else 1.0
    return [[max(-qmax, min(qmax, round(x/scale))) for x in values], scale]
`,[{expression:'quantize([-1,0,1],8)',expected:[[-127,0,127],1/127]},{expression:'quantize([0,0],4)',expected:[[0,0],1]},{expression:'quantize([],8)',expected:[[],1]},{expression:'quantize([-3,1,3],3)',expected:[[-3,1,3],1]},{expression:'quantize([.5,1.5,3],3)',expected:[[0,2,3],1]},{expression:'quantize([-2,2],2)',expected:[[-1,1],2]}],b('先用最大绝对值决定对称动态范围，再用 scale 映射到整数格点。零向量要避免除零，空列表也应有明确输出。\n\n这里没有 zero-point，且不用有符号整数范围中的最小不对称值（如 -128）。它是量化算术练习，不是 GPU INT8 kernel benchmark。','Use the maximum magnitude to set symmetric range, then map values to integer grid points via scale. Handle zero vectors and empty input explicitly.\n\nThere is no zero-point, and the asymmetric minimum (e.g. -128) is unused. This exercises quantization arithmetic, not GPU INT8 kernel performance.'),b('时间 O(n)，输出空间 O(n)。','O(n) time and output space.'),b('若每行权重使用独立 scale，精度与元数据成本如何变化？','How would row-wise scales affect precision and metadata costs?')),
code(56,'rag','medium',b('实现 Reciprocal Rank Fusion','Implement reciprocal rank fusion'),b('实现 rrf(rankings,k=60)。rankings 是多条按优先级排列的文档 ID 列表；ID 是字符串，每条列表内无重复。某文档在某列表 rank 从 1 开始，得分贡献 1/(k+rank)。跨列表累加，返回按总分降序排列的 ID，分数相同按字符串字典序升序。k 为非负整数。','Implement rrf(rankings,k=60). Each ranking contains unique string document IDs in priority order. A document at one-based rank contributes 1/(k+rank). Sum across lists and return IDs by descending score; break ties lexicographically ascending. k is a nonnegative integer.'),'def rrf(rankings, k=60):\n    pass\n',
`def rrf(rankings, k=60):
    scores = {}
    for ranking in rankings:
        for rank, doc in enumerate(ranking, 1):
            scores[doc] = scores.get(doc, 0.0) + 1/(k+rank)
    return sorted(scores, key=lambda doc: (-scores[doc], doc))
`,[{expression:"rrf([['a','b'],['b','c']])",expected:['b','a','c']},{expression:"rrf([['z'],['a']],0)",expected:['a','z']},{expression:'rrf([])',expected:[]},{expression:"rrf([[],['x']])",expected:['x']},{expression:"rrf([['c','a','b'],['b','a','c']],0)",expected:['b','c','a']}],b('RRF 融合的是 rank，而不是直接相加可能不可比较的 BM25 分数和 cosine 分数。每条排名从 1 开始，避免 k=0 时分母为零。\n\n它不使用标签，也不自动去除语义重复文档。实际系统还需评测融合后召回和上下文覆盖。','RRF fuses ranks instead of directly adding potentially incomparable BM25 and cosine scores. Start ranks at one to avoid division by zero at k=0.\n\nIt uses no relevance labels and does not automatically remove semantic duplicates. Evaluate fused recall and context coverage separately.'),b('总条目 N、唯一文档 U：O(N+U log U) 时间，O(U) 空间。','For N entries and U unique documents: O(N+U log U) time, O(U) space.'),b('为什么用排名融合时仍需要保留各检索器原始分数供诊断？','Why retain original retriever scores for diagnosis even when fusing ranks?')),
code(57,'agents','hard',b('校验工具调用边界','Validate a tool-call boundary'),b('实现 validate_call(text,schemas)。解析 JSON；顶层必须恰好含 tool 与 args，tool 是 schemas 中的字符串键，args 是字典且键恰好匹配该工具 schema。Schema 将参数名映射到 "str" 或 "int"；int 必须是 Python int 且不是 bool。不符合任何规则或 JSON 不合法时抛 ValueError，成功返回解析后的字典。此函数不执行工具，也不代替业务授权。','Implement validate_call(text,schemas). Parse JSON. Top level must contain exactly tool and args; tool must be a string key in schemas. args must be a dictionary with exactly the schema’s keys. Schemas map argument names to "str" or "int"; int must be a Python int, not bool. Raise ValueError for any invalid input or malformed JSON; otherwise return the parsed dictionary. Do not execute tools; this does not replace authorization.'),'def validate_call(text, schemas):\n    pass\n',
`import json
def validate_call(text, schemas):
    try:
        call = json.loads(text)
    except (ValueError, TypeError):
        raise ValueError('Invalid JSON')
    if type(call) is not dict or set(call) != {'tool', 'args'}:
        raise ValueError('Invalid shape')
    if type(call['tool']) is not str or call['tool'] not in schemas:
        raise ValueError('Unknown tool')
    args = call['args']
    schema = schemas[call['tool']]
    if type(args) is not dict or set(args) != set(schema):
        raise ValueError('Invalid arguments')
    for key, kind in schema.items():
        expected = {'str': str, 'int': int}[kind]
        if type(args[key]) is not expected:
            raise ValueError('Invalid type')
    return call
`,[{expression:`validate_call('{"tool":"search","args":{"q":"llm"}}',{'search':{'q':'str'}})`,expected:{tool:'search',args:{q:'llm'}}},{expression:`validate_call('{"tool":"limit","args":{"n":3}}',{'limit':{'n':'int'}})`,expected:{tool:'limit',args:{n:3}}},{expression:`validate_call('{"tool":"limit","args":{"n":true}}',{'limit':{'n':'int'}})`,raises:'ValueError'},{expression:`validate_call('{"tool":"delete","args":{}}',{'search':{'q':'str'}})`,raises:'ValueError'},{expression:`validate_call('{"tool":"search","args":{"q":"x","extra":1}}',{'search':{'q':'str'}})`,raises:'ValueError'},{expression:`validate_call('[]',{})`,raises:'ValueError'},{expression:`validate_call('not json',{})`,raises:'ValueError'},{expression:`validate_call('{"tool":"search","args":{}}',{'search':{'q':'str'}})`,raises:'ValueError'}],b('分层验证：JSON 解析、顶层结构、工具白名单、参数键集合、参数类型。Python 的 bool 是 int 子类，因此 isinstance(True,int) 会误放行，要检查精确类型。\n\n校验通过仍不代表有权限执行：用户身份、配额、资源范围与副作用确认必须由执行层独立控制。','Validate parsing, top-level shape, tool allowlist, exact argument keys, then types. Python bool subclasses int, so isinstance(True,int) would incorrectly accept a boolean; use exact type checks.\n\nPassing validation is not authorization. Identity, quotas, resource scope and side-effect confirmation require separate execution-layer controls.'),b('时间 O(JSON 长度+参数数)，空间 O(JSON 长度)。','O(JSON length + argument count) time; O(JSON length) space.'),b('需要防止重复 JSON 键或极大输入时，你会加什么限制？','How would you handle duplicate JSON keys and excessively large inputs?')),
code(58,'multimodal','medium',b('实现二维 Patchify','Implement 2D patchify'),b('实现 patchify(image,p)。image 是非空二维数值列表，p 为正整数。若行长度不一致或图像任一边不能被 p 整除，抛 ValueError。按 patch 的行优先顺序输出，每个 p×p patch 内也按行优先展开为一维列表。若 image 为空或宽度为 0，也抛 ValueError。','Implement patchify(image,p), with positive integer p. image is a 2D numeric list. Raise ValueError for empty input, zero width, ragged rows, or dimensions not divisible by p. Return patches in row-major order, flattening each p×p patch row-major as well.'),'def patchify(image, p):\n    pass\n',
`def patchify(image, p):
    if not image or not image[0]:
        raise ValueError('Empty image')
    h, w = len(image), len(image[0])
    if any(len(row) != w for row in image) or h % p or w % p:
        raise ValueError('Invalid shape')
    return [[image[r+i][c+j] for i in range(p) for j in range(p)]
            for r in range(0,h,p) for c in range(0,w,p)]
`,[{expression:'patchify([[1,2],[3,4]],2)',expected:[[1,2,3,4]]},{expression:'patchify([[1,2,3,4],[5,6,7,8]],2)',expected:[[1,2,5,6],[3,4,7,8]]},{expression:'patchify([[1,2],[3,4]],1)',expected:[[1],[2],[3],[4]]},{expression:'patchify([[1,2,3],[4,5,6]],2)',raises:'ValueError'},{expression:'patchify([[1,2],[3]],1)',raises:'ValueError'},{expression:'patchify([],1)',raises:'ValueError'},{expression:'patchify([[]],1)',raises:'ValueError'}],b('先验证矩形与整除约束，再遍历 patch 左上角。两层外循环控制 patch 位置，两层内循环控制 patch 内像素顺序。\n\n这一步只重排像素，不是 learned patch embedding；后续线性投影和位置编码是另外的操作。','Validate rectangular shape and divisibility, then iterate patch origins. Outer loops determine patch order; inner loops determine pixel order within each patch.\n\nThis only rearranges pixels. Learned patch projection and positional encoding are separate operations.'),b('时间和输出空间 O(HW)。','O(HW) time and output space.'),b('RGB 图像 flatten 时通道顺序如何与模型训练保持一致？','How do you keep RGB channel ordering consistent with training?')),
code(59,'recommendation','medium',b('合法 Semantic ID 的下一步','Valid next tokens for semantic IDs'),b('实现 next_tokens(sequences,prefix)。sequences 是合法 ID 序列列表，每个 ID 是整数列表；prefix 是整数列表。返回所有以 prefix 开头的 ID 中紧随其后的 token，去重并升序。已恰好结束的 ID 不贡献 token；本题不添加 EOS。空前缀匹配所有 ID。','Implement next_tokens(sequences,prefix). Each valid ID in sequences is an integer list, as is prefix. Return unique, sorted tokens immediately following prefix in matching IDs. IDs ending exactly at prefix contribute no token; do not add EOS. An empty prefix matches every ID.'),'def next_tokens(sequences, prefix):\n    pass\n',
`def next_tokens(sequences, prefix):
    n = len(prefix)
    return sorted({seq[n] for seq in sequences if len(seq)>n and seq[:n]==prefix})
`,[{expression:'next_tokens([[1,2,3],[1,2,4],[1,5]],[1,2])',expected:[3,4]},{expression:'next_tokens([[2],[1,3],[]],[])',expected:[1,2]},{expression:'next_tokens([[1,2]],[1,2])',expected:[]},{expression:'next_tokens([[1,2],[1,2]],[1])',expected:[2]},{expression:'next_tokens([[1,2]],[9])',expected:[]},{expression:'next_tokens([],[])',expected:[]}],b('只接受与完整 prefix 匹配且仍有后续 token 的序列。集合消除重复，排序使结果可复现。\n\n参考实现直接扫描，适合说明规则。大量反复查询应预构建 Trie，用更低查询成本换预处理和存储；还需单独处理真实系统里的终止符。','Accept IDs matching the entire prefix and containing a next token. A set removes duplicates; sorting makes output deterministic.\n\nThe reference scans directly to illustrate the rule. Repeated large-scale queries should use a prebuilt trie, trading preprocessing and storage for cheaper lookup, with explicit termination handling.'),b('N 条序列、前缀长 P、候选 U：O(NP+U log U) 时间，额外 O(P+U) 空间。','For N sequences, prefix length P and U candidates: O(NP+U log U) time, O(P+U) extra space.'),b('商品下架后，Trie 和缓存怎样保持一致？','How would you keep trie and cache state consistent after item removal?')),
code(60,'evaluation','medium',b('实现 NDCG@k','Implement NDCG@k'),b('实现 ndcg(relevance,k)。relevance 是当前排序的非负整数相关性列表，k 是非负整数。DCG@k = Σ(2^rel_i−1)/log2(i+2)，i 从 0 开始；IDCG 使用同一列表降序后的前 k 项。IDCG=0 时返回 0，k 超过列表长度时只计算现有项。','Implement ndcg(relevance,k), where relevance is a ranked list of nonnegative integer grades and k is a nonnegative integer. DCG@k = Σ(2^rel_i−1)/log2(i+2), with zero-based i. IDCG uses the top k grades from this same list sorted descending. Return 0 if IDCG=0; if k exceeds the list length, use available items.'),'def ndcg(relevance, k):\n    pass\n',
`import math
def ndcg(relevance, k):
    def dcg(values):
        return sum((2**grade-1)/math.log2(i+2) for i,grade in enumerate(values[:k]))
    ideal = dcg(sorted(relevance, reverse=True))
    return dcg(relevance)/ideal if ideal else 0.0
`,[{expression:'ndcg([3,2,1],3)',expected:1},{expression:'ndcg([0,1],2)',expected:.63092975357},{expression:'ndcg([0,0],2)',expected:0},{expression:'ndcg([],3)',expected:0},{expression:'ndcg([3,2],0)',expected:0},{expression:'ndcg([1,0],20)',expected:1},{expression:'ndcg([0,3],1)',expected:0}],b('先计算当前顺序的折扣收益，再用同一候选集合的理想排序归一化。rank 从 1 开始时折扣为 log2(rank+1)，所以零下标实现用 i+2。\n\n这是题目指定的候选集合内 NDCG；真实召回评测的 ideal 集合可能包含未召回的相关项，必须先统一协议。','Compute discounted gain in the current order and normalize by the ideal ordering of the same candidate set. One-based ranks use log2(rank+1), hence i+2 for zero-based indices.\n\nThis is the specified candidate-set NDCG. In retrieval evaluation, the ideal set may include relevant items not retrieved; agree on the protocol first.'),b('排序占主导：O(n log n) 时间、O(n) 空间。','Sorting dominates: O(n log n) time, O(n) space.'),b('为什么不同 relevance gain 定义会改变 NDCG 的解释？','Why does changing the relevance-gain definition change NDCG interpretation?')),
];
