'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {classify,decode,encode,maskOrder,pixelMask,project,reconstruct,type ReconstructionModel} from '@/lib/reconstruction/model';
import PixelImage from './PixelImage';
const emptyMask=Array(16).fill(0) as number[];
export default function ReconstructionLab({en=false}:{en?:boolean}){
 const t=(zh:string,eng:string)=>en?eng:zh;
 const [model,setModel]=useState<ReconstructionModel|null>(null),[failed,setFailed]=useState(false),[attempt,setAttempt]=useState(0);
 const [sample,setSample]=useState(16),[custom,setCustom]=useState<number[]|null>(null),[mode,setMode]=useState<'mask'|'draw'>('mask');
 const [mask,setMask]=useState<number[]>(()=>maskOrder(73).map((_,i)=>i<8?1:0)),[seed,setSeed]=useState(73),[wipe,setWipe]=useState(100),[alpha,setAlpha]=useState(0),[target,setTarget]=useState(6);
 const painting=useRef<{active:boolean;value:number}>({active:false,value:0});
 useEffect(()=>{const controller=new AbortController();fetch('/models/reconstruction/model.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('load');return r.json()}).then((m:ReconstructionModel)=>{setModel(m);setFailed(false);const order=maskOrder(73);setMask(emptyMask.map((_,i)=>order.indexOf(i)<8?1:0))}).catch(e=>{if(e.name!=='AbortError')setFailed(true)});return()=>controller.abort()},[attempt]);
 const pixels=custom??model?.gallery[sample].pixels??Array(64).fill(0),count=mask.reduce((s,v)=>s+v,0);
 const result=useMemo(()=>model?reconstruct(model,pixels,mask):null,[model,pixels,mask]);
 const intact=useMemo(()=>model?classify(model,encode(model,pixels,emptyMask)):null,[model,pixels]);
 const end=useMemo(()=>model?encode(model,model.gallery[target].pixels,emptyMask):null,[model,target]);
 const mixed=useMemo(()=>model&&result&&end?result.latent.map((v,i)=>v*(1-alpha)+end[i]*alpha):null,[model,result,end,alpha]);
 const generated=useMemo(()=>model&&mixed?decode(model,mixed):null,[model,mixed]);
 const mixedXY=model&&mixed?project(model,mixed):null;
 function setRatio(n:number,nextSeed=seed){const order=maskOrder(nextSeed);setMask(emptyMask.map((_,i)=>order.indexOf(i)<n?1:0))}
 function edit(i:number,value?:number){if(mode==='mask')setMask(m=>m.map((v,j)=>j===i?(value??1-v):v));else setCustom(p=>{const next=[...(p??pixels)];next[i]=value??(next[i]>.5?0:1);return next})}
 function pointer(e:React.PointerEvent<HTMLDivElement>,start=false){if(start&&e.button!==0)return;const box=e.currentTarget.getBoundingClientRect();const n=mode==='mask'?4:8,c=Math.min(n-1,Math.max(0,Math.floor((e.clientX-box.left)/box.width*n))),r=Math.min(n-1,Math.max(0,Math.floor((e.clientY-box.top)/box.height*n))),i=r*n+c;if(start){painting.current={active:true,value:mode==='mask'?1-mask[i]:pixels[i]>.5?0:1};e.currentTarget.setPointerCapture(e.pointerId)}if(painting.current.active)edit(i,painting.current.value)}
 function exportTrace(){if(!result||!model)return;const blob=new Blob([JSON.stringify({model:model.meta,pixels,mask,...result},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reconstruction-trace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const winner=result?result.probabilities.indexOf(Math.max(...result.probabilities)):0;
 const rank=result?result.probabilities.map((p,id)=>({p,id})).sort((a,b)=>b.p-a.p):[];
 const cloud=model?.cloud??[],xs=cloud.map(p=>p.xy[0]),ys=cloud.map(p=>p.xy[1]);
 const xmin=Math.min(...xs,-1)-.5,xmax=Math.max(...xs,1)+.5,ymin=Math.min(...ys,-1)-.5,ymax=Math.max(...ys,1)+.5;
 const xy=(p:number[])=>[20+(p[0]-xmin)/(xmax-xmin)*380,200-(p[1]-ymin)/(ymax-ymin)*180];
 return <main className="rc-shell" lang={en?'en':'zh-CN'}>
  <header className="rc-header"><a href="/">Huiyu Chen <span>/</span> LAB</a><nav><a href="/lab/transformer">001 · Transformer</a><a href={en?'/lab/reconstruction':'/lab/reconstruction/en'}>{en?'中文':'EN'}</a></nav></header>
  <div className="rc-title"><div><p className="rc-kicker">EXPERIMENT 002 / THE MISSING PIECE</p><h1>{t('缺失的部分，如何被理解？','What lives in the missing pieces?')}</h1></div><p>{t('遮住笔画，重建图像。再问一次：它知道自己看见了什么吗？','Hide a stroke. Reconstruct the image. Then ask: does it know what it sees?')}</p></div>
  {!model?<section className="rc-loading" role="status">{failed?<><p>{t('模型加载失败，请重试。','The model could not load. Please retry.')}</p><button onClick={()=>{setFailed(false);setAttempt(v=>v+1)}}>{t('重试','Retry')}</button></>:t('正在加载本站训练的重建模型…','Loading the reconstruction model trained for this site…')}</section>:result&&intact&&end&&generated&&<>
  <section className="rc-toolbar" aria-label={t('实验控制','Experiment controls')}><div className="rc-samples"><span>{t('选择测试样本','TEST SAMPLES')}</span><div>{Array.from({length:10},(_,n)=><button key={n} aria-pressed={!custom&&model.gallery[sample].label===n} onClick={()=>{setSample(n*2);setCustom(null);setMode('mask');setAlpha(0)}}>{n}</button>)}</div><button onClick={()=>{setSample(s=>s%2?s-1:s+1);setCustom(null)}}>{t('另一种写法','Other handwriting')} ↻</button></div><div className="rc-masking"><label htmlFor="rc-ratio">{t('遮挡比例','MASK RATIO')} <strong>{Math.round(count/16*100)}%</strong></label><input id="rc-ratio" type="range" min="0" max="16" value={count} onChange={e=>setRatio(Number(e.target.value))}/><button onClick={()=>{setSeed(s=>s+1);setRatio(count,seed+1)}}>{t('重新遮挡','Reshuffle')} ↻</button></div></section>
  <section className="rc-triptych">
   <article className="rc-panel"><div className="rc-panel-title"><h2>01 / {t('可见的证据','VISIBLE EVIDENCE')}</h2><span>{16-count}/16 PATCHES</span></div><div className="rc-image rc-editable" onPointerDown={e=>pointer(e,true)} onPointerMove={e=>pointer(e)} onPointerUp={()=>{painting.current.active=false}} onPointerCancel={()=>{painting.current.active=false}}><PixelImage pixels={pixels} mask={mode==='mask'?mask:undefined} label={t('模型输入；点击或拖动编辑','Model input; click or drag to edit')}/><div className="rc-edit-grid" style={{gridTemplateColumns:`repeat(${mode==='mask'?4:8},1fr)`}}>{Array.from({length:mode==='mask'?16:64},(_,i)=><button key={`${mode}-${i}`} aria-label={`${mode==='mask'?t('遮挡块','Mask patch'):t('画笔像素','Draw pixel')} ${i}`} aria-pressed={mode==='mask'?!!mask[i]:pixels[i]>.5} onClick={e=>{if(e.detail===0)edit(i)}}/>)}</div></div><div className="rc-edit-modes"><button aria-pressed={mode==='mask'} onClick={()=>setMode('mask')}>{t('遮挡 / 恢复','Mask / reveal')}</button><button aria-pressed={mode==='draw'} onClick={()=>setMode('draw')}>{t('修改笔画','Edit strokes')}</button><button onClick={()=>{setCustom(Array(64).fill(0));setMode('draw');setMask([...emptyMask])}}>{t('清空手写','Draw from blank')}</button></div><p>{mode==='draw'?t('拖动画出笔画；再次划过可擦除。这里编辑原始 8×8 像素，切回遮挡模式看模型输入。','Drag to draw a stroke; start on a bright pixel to erase. This edits the original 8×8 pixels. Switch back to Mask to see the model input.'):t('点击或划过一个 2×2 patch，把它遮住或恢复。隐藏像素在进入编码器前已清零。','Click or brush over a 2×2 patch to hide or reveal it. Hidden pixels are zeroed before reaching the encoder.')}</p></article>
   <article className="rc-panel"><div className="rc-panel-title"><h2>02 / {t('重建的假设','RECONSTRUCTED HYPOTHESIS')}</h2><span>DECODER</span></div><div className="rc-image rc-compare"><PixelImage pixels={pixels} label={t('原始图像','Original image')}/><div className="rc-overlay" style={{clipPath:`inset(0 ${100-wipe}% 0 0)`}}><PixelImage pixels={result.composite} label={t('可见像素保留原值，被遮挡像素使用模型输出','Visible pixels kept; hidden pixels filled by model prediction')}/></div><i className="rc-wipe-line" style={{left:`${wipe}%`}}/></div><label className="rc-wipe-label" htmlFor="rc-wipe"><span>{t('原图','Original')}</span><input id="rc-wipe" type="range" min="0" max="100" value={wipe} onChange={e=>setWipe(Number(e.target.value))}/><span>{t('重建','Reconstruction')}</span></label><p>{t('拖动比较。可见区域保留原像素；只有被遮住的区域由解码器填入。模型提出的是一个猜测，不是恢复了唯一真相。','Slide to compare. Visible pixels are preserved; only hidden regions use the decoder output. This is a prediction, not recovery of a uniquely determined truth.')}</p></article>
   <article className="rc-panel"><div className="rc-panel-title"><h2>03 / {t('猜错的地方','WHERE IT MISSES')}</h2><span>SQUARED ERROR</span></div><div className="rc-image"><PixelImage pixels={result.errors.map((v,i)=>pixelMask(mask)[i]?v:0)} heat label={t('被遮挡像素的平方误差热图，固定范围零到一','Squared error on masked pixels, fixed range zero to one')}/></div><div className="rc-error-scale"><span>0</span><i/><span>1</span><strong>{result.mse===null?'—':result.mse.toFixed(4)} <small>MSE</small></strong></div><p>{count?t('误差只统计被遮挡的像素，色标固定为 [0,1]。像素越亮，预测与原图的差异越大。','Error is measured only on masked pixels, on a fixed [0,1] scale. Brighter pixels differ more from the original.'):t('没有被遮挡的像素，所以 masked MSE 没有定义。试着遮住一部分。','No pixels are masked, so masked MSE is undefined. Hide a few patches to begin.')}</p></article>
  </section>
  {count===16&&<p className="rc-alert">{t('所有证据都被遮住了。现在的输出只来自学习到的先验，与这张原图的内容无关；100% 遮挡也超出了训练范围。','All evidence is hidden. The output now depends only on learned priors, not this original image. 100% masking is also outside the training range.')}</p>}
  <section className="rc-understanding"><div className="rc-question"><p className="rc-kicker">RECONSTRUCTION ≠ UNDERSTANDING</p><h2>{t('补得像，就理解了吗？','Does looking right mean understanding?')}</h2><p>{t('同一个 24 维表示，走两条路：解码器预测像素；另一个线性分类器判断数字。前者用图像训练，后者在编码器冻结后才使用数字标签。','The same 24-dimensional representation takes two paths: a decoder predicts pixels, while a separate linear probe predicts the digit. The first learns from images; the second uses labels only after the encoder is frozen.')}</p><div className="rc-verdict"><strong>{winner}</strong><span>{t('当前表示的首选类别','Current representation’s top class')}<b>{(result.probabilities[winner]*100).toFixed(1)}%</b></span><span>{t('参考标签','Reference label')}<b>{custom?'—':model.gallery[sample].label}</b></span></div><p className="rc-fine">{t('分类器概率未经校准，不是“理解程度”。你手写或修改的图没有已知标签，也可能偏离训练分布。','Probe probabilities are uncalibrated, not a measure of understanding. Edited or drawn inputs have no known label and may be out of distribution.')}</p></div><div className="rc-probs"><div className="rc-legend"><span><i/>{t('完整原图','Intact image')}</span><span><i className="current"/>{t('当前遮挡','Current mask')}</span></div>{rank.map(({p,id})=><div className="rc-prob" key={id}><span>{id}</span><div><i style={{width:`${intact[id]*100}%`}}/><b style={{width:`${p*100}%`}}/></div><span>{(p*100).toFixed(1)}%</span></div>)}</div></section>
  <section className="rc-latent"><div className="rc-latent-intro"><p className="rc-kicker">WALK THROUGH THE LATENT SPACE</p><h2>{t('在表示之间漫游。','Walk between representations.')}</h2><p>{t('从当前遮挡输入的 z 出发，走向另一个完整样本的 z。每一步都把插值后的向量送回解码器，生成全图。','Start at z from the current masked input and move toward z from another intact sample. Every step feeds the interpolated vector into the decoder to generate the entire image.')}</p><label>{t('终点数字','Destination digit')}<select value={target} onChange={e=>setTarget(Number(e.target.value))}>{Array.from({length:10},(_,n)=><option key={n} value={n*2}>{n}</option>)}</select></label><label htmlFor="rc-alpha">z(α) = (1−α) z₀ + α z₁ <strong>α = {alpha.toFixed(2)}</strong></label><input id="rc-alpha" type="range" min="0" max="1" step=".01" value={alpha} onChange={e=>setAlpha(Number(e.target.value))}/><p className="rc-fine">{t('这不是图像淡入淡出。中间态不一定是有效数字；生成连贯不等于语义正确。','This is not an image crossfade. Intermediate states need not be valid digits; smooth generation does not establish semantic correctness.')}</p></div><div className="rc-latent-image"><PixelImage pixels={generated} label={t('潜向量插值后的真实解码结果','Actual decoder output from the interpolated latent vector')}/><span>{t('全部像素由解码器生成','ALL PIXELS GENERATED BY DECODER')}</span></div><div className="rc-pca"><svg viewBox="0 0 420 220" role="img" aria-label={t('潜表示的二维 PCA 投影，样本点、起点和终点之间的轨迹','Two-dimensional PCA projection of latent representations with samples and interpolation path')}><title>{t('PCA 是有损投影，不是完整的语义距离','PCA is a lossy projection, not the full semantic distance')}</title>{cloud.map((p,i)=>{const a=xy(p.xy);return <circle key={i} cx={a[0]} cy={a[1]} r="2.5" fill={`hsl(${p.label*36} 55% 65%)`} opacity=".55"><title>{`digit ${p.label}`}</title></circle>})}{(()=>{const a=xy(result.xy),b=xy(project(model,end)),c=xy(mixedXY!);return <><line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke="#ecdb8a" strokeWidth="1" strokeDasharray="4 4"/><circle cx={a[0]} cy={a[1]} r="5" stroke="#c9f2d4" strokeWidth="1.5" fill="none"/><rect x={b[0]-4} y={b[1]-4} width="8" height="8" stroke="#ecdb8a" fill="none"/><circle cx={c[0]} cy={c[1]} r="5" fill="#ecdb8a"/></>})()}</svg><div className="rc-cloud-legend">{Array.from({length:10},(_,n)=><span key={n} style={{color:`hsl(${n*36} 55% 65%)`}}>{n}</span>)}</div><p>{t('圆点：当前输入；方框：终点。背景为 180 个测试样本的完整图像表示，按真实数字着色。','Circle: current input. Square: destination. Background: intact representations of 180 test images, coloured by their true digit.')}</p><p>{t('前两个主成分保留的方差','Variance retained by the first two PCs')}: {(model.pca.variance.reduce((a,b)=>a+b,0)*100).toFixed(1)}%.</p></div></section>
  <div className="rc-model-line"><span>{model.meta.parameters.toLocaleString('en-US')} {t('重建参数','AE PARAMETERS')} + 250 {t('分类器参数 · 浏览器本地计算','PROBE PARAMETERS · LOCAL INFERENCE')}</span><button onClick={exportTrace}>{t('导出像素与潜向量','Export pixels & latent vectors')} ↓</button></div>
  <section className="rc-notes"><div className="rc-notes-heading"><p className="rc-kicker">FROM RECONSTRUCTION TO CONTENT UNDERSTANDING</p><h2>{t('把这条技术链真正串起来。','Connect the whole learning loop.')}</h2></div>
   <article><span>01 / TASK</span><h3>{t('为什么故意把图像弄坏？','Why deliberately damage an image?')}</h3><p>{t('直接复制输入，可以拿到很低的重建误差，却不必学会结构。遮挡让这条捷径失效：编码器只收到可见像素和可见性标记。想预测被遮住的笔画，就要利用剩余区域之间的规律。训练目标来自原图本身，因此这个阶段不需要“这是 8”这样的类别标签。这里每张图有 16 个 patch，每个 patch 包含 2×2 个像素。','Copying an input can achieve low reconstruction error without learning structure. Masking blocks this shortcut: the encoder receives only visible pixels and visibility flags. To predict missing strokes, it must exploit regularities among the remaining regions. The original image supplies the targets, so this phase needs no class label such as “8”. Each image here has 16 patches of 2×2 pixels.')}</p><p>{t('试验：选同一张图，先随机遮 50%，再集中遮住左半边。数量相同，信息量却不相同。遮住背景和遮住区分 3 与 8 的关键笔画，任务难度当然不同。','Try the same image with 50% random masking, then mask its entire left half. Equal patch counts do not imply equal information. Hiding background differs from hiding the stroke that distinguishes a 3 from an 8.')}</p></article>
   <article><span>02 / OBJECTIVE</span><h3>{t('重建误差究竟量了什么？','What does reconstruction error measure?')}</h3><p>{t('页面的 masked MSE 是：把每个隐藏像素的“预测值减真实值”平方，再取平均。黑白强度在 [0,1]，所以平方误差也在 [0,1]。可见区域即使复制得完美，也不会拉低这个指标。这里的热图使用相同的固定范围，避免不同实验各自缩放后看上去一样好。','Masked MSE averages the squared difference between predicted and true intensity over hidden pixels only. Intensities lie in [0,1], so squared errors do too. Perfectly copying the visible region cannot lower this metric. The heatmap uses a fixed scale so separate experiments are comparable.')}</p><p>{t('MSE 惩罚像素差异，不直接奖励“仍然是同一个数字”。当多个补全都合理时，预测平均形态可能更容易降低平方误差，结果就会发糊。反过来，一处很小的笔画变化可能只产生较小 MSE，却把一个数字变成另一个数字。','MSE penalizes pixel differences; it does not directly reward retaining the same digit identity. When multiple completions are plausible, predicting their average can reduce squared error and produce blur. Conversely, a small stroke change can have modest MSE yet change the digit’s identity.')}</p></article>
   <article><span>03 / REPRESENTATION</span><h3>{t('理解能力在哪里检查？','Where do we test recognition?')}</h3><p>{t('编码器把 64 个像素和 16 个可见性标记压成 24 个数 z。解码器从 z 重建图像；线性 probe 从同一个 z 预测 0–9。这次先只用重建目标训练编码器，再冻结它，最后才用类别标签训练 probe。因此，识别成绩检验的是：这个固定表示里，有多少类别信息能被一个简单分类器读出来。它不是模型“像人一样理解”的证明。','The encoder compresses 64 pixels and 16 visibility flags into 24 numbers, z. The decoder reconstructs an image from z; a linear probe predicts 0–9 from the same z. We train the encoder using reconstruction, freeze it, then train the probe using class labels. Recognition measures how much class information a simple classifier can read from that fixed representation. It does not establish human-like understanding.')}</p><p>{t('同时看两件事：masked MSE 是否下降，分类器是否仍认得参考数字。如果指标方向不同，恰好说明 reconstruction 和 content understanding 不是同一个优化目标。','Track both masked MSE and whether the probe still recognizes the reference digit. If they move in different directions, that illustrates why reconstruction and content understanding are distinct objectives.')}</p></article>
   <article><span>04 / TRANSFER</span><h3>{t('从这个实验走向 MAE 和多模态。','From this experiment to MAE and multimodal learning.')}</h3><p>{t('这里运行的是 MLP masked autoencoder，不是原论文的 ViT MAE。MAE 用只处理可见 patch 的编码器，再用轻量解码器补回遮挡区域；这个实验用“像素清零 + 可见性标记”实现同一个遮挡预测问题，结构更小。不要把本实验的遮挡比例或识别成绩当成 MAE 在自然图像上的结论。','This runs an MLP masked autoencoder, not the paper’s ViT MAE. MAE encodes only visible patches and uses a lightweight decoder to reconstruct masked regions. This smaller experiment instead uses zeroed pixels plus visibility flags. Its mask ratios and recognition scores do not establish MAE performance on natural images.')} <a href="https://arxiv.org/abs/2111.06377">MAE paper ↗</a></p><p>{t('在真实 content understanding 流程中，重建可以作为预训练信号。下游仍需独立检验分类、检索或定位；多模态还要验证图像和文本等模态之间的语义对应。能补笔画、能认数字、能理解一张复杂照片的内容，是不同层次的证据。','In a content-understanding pipeline, reconstruction can provide a pretraining signal. Downstream classification, retrieval and localization still require their own evaluations; multimodal systems also need cross-modal semantic alignment. Completing strokes, recognizing digits and interpreting a complex photograph require different evidence.')}</p></article>
   <article className="rc-model-card"><span>05 / MODEL RECORD</span><h3>{t('模型与数据，可以复查。','The model and data are inspectable.')}</h3><p>{t('数据来自 sklearn 随附的 UCI 手写数字集：1,797 张 8×8 灰度图。固定种子 73，按类别分层划分 1,437 张训练图和 360 张测试图；这不是按书写者隔离的评测。上方样本来自测试集，每个数字取测试划分中的前两个，没有按重建好坏筛选。所有新输出都在浏览器中用本站权重计算。','Data comes from sklearn’s bundled UCI handwritten digits: 1,797 grayscale 8×8 images. Seed 73 gives a stratified split of 1,437 training and 360 test images; this is not writer-disjoint evaluation. The gallery uses the first two test images of each digit, without filtering for reconstruction quality. All new outputs are computed in the browser using weights from this site.')} <a href="https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html">Dataset ↗</a> · Alpaydin &amp; Kaynak (1998) · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> · <a href="/models/reconstruction/NOTICE.txt">{t('数据处理说明','Data adaptations')}</a></p><div className="rc-benchmarks"><div><span>{t('完整图 probe 准确率','Intact-image probe accuracy')}</span><strong>{(model.meta.metrics.cleanProbeAccuracy*100).toFixed(1)}%</strong></div><div><span>{t('随机遮 50% probe 准确率','50%-masked probe accuracy')}</span><strong>{(model.meta.metrics.halfMaskedProbeAccuracy*100).toFixed(1)}%</strong></div><div><span>{t('遮 50% 的模型 / 均值填充 MSE','50%-masked model / mean-fill MSE')}</span><strong>{model.meta.metrics.halfMaskedMSE.toFixed(4)} / {model.meta.metrics.meanFillMSE.toFixed(4)}</strong></div></div><p>{t('以上是固定测试遮挡下的记录，不随当前操作变化。重建训练 3,500 步，目标是 masked MSE + 0.1 × visible MSE，随机遮 0–13 个 patch；编码器冻结后，线性 probe 训练 1,600 步。均值填充基线使用训练集每个像素的平均值。PCA 也仅用训练表示拟合；二维投影会丢失信息。','These are recorded test results with fixed test masks, not live metrics. Reconstruction trains for 3,500 steps with masked MSE + 0.1 × visible MSE and 0–13 random masked patches. The frozen-encoder linear probe trains for 1,600 steps. Mean filling uses per-pixel training-set averages. PCA is fitted only on training representations; its 2D projection loses information.')}</p><div className="rc-links"><a href="https://github.com/chenhuiyu/chenhuiyu.github.io/blob/source/scripts/train-reconstruction.py">{t('完整训练代码','Full training code')} ↗</a><a href="/models/reconstruction/model-card.json">{t('模型记录','Model record')} ↗</a><a href={en?'/blog/multimodal-reconstruction-en':'/blog/multimodal-reconstruction-zh'}>{t('深入阅读 Reconstruction','Read the reconstruction chapter')} ↗</a></div></article>
  </section></>}
  <footer className="rc-footer"><a href="/lab/transformer">← {t('Transformer 解剖台','Transformer observatory')}</a><a href={en?'/learn/multimodal/en':'/learn/multimodal'}>{t('多模态学习路线','Multimodal learning path')} ↗</a></footer>
 </main>
}
